package com.mukundafoods.chimneylauncherproduct.ui.mqtt

object MQTTConstants {
    const val CHIMNEY_CONTROL_SCREEN_NAME = "ChimneyControl"
    const val CHIMNEY_CONTROL_BLOWER_REDUCE = "Blower reduce"
    const val CHIMNEY_CONTROL_BLOWER_INCREASE = "Blower increase"

    const val CHIMNEY_CONTROL_TURBO_CLICKED = "Turbo Mode"
    const val CHIMNEY_CONTROL_BLOWER_ON = "Blower on"
    const val CHIMNEY_CONTROL_BLOWER_OFF = "Blower off"
    const val CHIMNEY_CONTROL_CHIMNEY_LIGHT = "Chimney Light"
    const val CHIMNEY_CONTROL_AUTO_START = "Chimney auto start"
    const val CHIMNEY_CONTROL_AUTO_STOP = "Chimney auto stop"
    const val CHIMNEY_CONTROL_TIMER_START = "Chimney timer start"
    const val CHIMNEY_CONTROL_TIMER_STOP = "Chimney timer stop"

    const val APPS_AND_MORE_SCREEN_NAME = "Apps and more"
    const val APPS_AND_MORE_SCREEN_OTT_APP = "Ott App"
    const val APPS_AND_MORE_SCREEN_YOUTUBE = "youtube"
    const val APPS_AND_MORE_SCREEN_NETFLIX = "netflix"
    const val APPS_AND_MORE_SCREEN_PRIME = "amazon prime"
    const val APPS_AND_MORE_SCREEN_DISNEY_HOT_STAR = "hotstar"
    const val APPS_AND_MORE_SCREEN_SONY_LIV = "sonyliv"
    const val APPS_AND_MORE_SCREEN_MUSIC_AUDIO = "music and audio"
    const val APPS_AND_MORE_SCREEN_YOUTUBE_MUSIC = "youtube music"
    const val APPS_AND_MORE_SCREEN_SPOTIFY = "soptify"
    const val APPS_AND_MORE_SCREEN_SAAVN = "saavan"
    const val APPS_AND_MORE_SCREEN_GAANA = "gaana"
    const val APPS_AND_MORE_SCREEN_AMAZON_MUSIC = "amazon music"
    const val APPS_AND_MORE_SCREEN_FOOD_AND_BEVARAGES = "food and beverages"
    const val APPS_AND_MORE_SCREEN_ZOMATO = "zomato"
    const val APPS_AND_MORE_SCREEN_LICIOUS = "licious"
    const val APPS_AND_MORE_SCREEN_SWIGGY = "swiggy"
    const val APPS_AND_MORE_SCREEN_ZEPTO = "zepto"
    const val APPS_AND_MORE_SCREEN_BLINK_IT = "blink it"
    const val APPS_AND_MORE_SCREEN_OTHER_APPS = "other apps"
    const val APPS_AND_MORE_SCREEN_NOTES = "notes"
    const val APPS_AND_MORE_SCREEN_NEWS = "news"
    const val APPS_AND_MORE_SCREEN_BROWSER = "browser"
    const val APPS_AND_MORE_SCREEN_LGP_REMINDER = "lpg reminder"

    const val CHEF_CONNECT_SCREEN_NAME = "Chef connet"
    const val CHEF_CONNECT_SCREEN_WOKIE = "wokie"
    const val CHEF_CONNECT_SCREEN_REMINDER = "reminder"
    const val CHEF_CONNECT_SCREEN_NOTES = "notes"
    const val CHEF_CONNECT_SCREEN_LPG_REMINDER = "lpg reminder"

    const val MAIN_ACTIVITY_SCREEN_NAME = "main activity"
    const val MAIN_ACTIVITY_SCREEN_WIFI = "wifi"
    const val MAIN_ACTIVITY_SCREEN_USB = "sub"
    const val MAIN_ACTIVITY_SCREEN_CLEAN = "clean"
    const val MAIN_ACTIVITY_SCREEN_SETTINGS = "settings"
    const val MAIN_ACTIVITY_SCREEN_ACCOUNT = "account"

    const val CLEANING_SCREEN_NAME = "cleaning"
    const val CLEANING_SCREEN_START_AUTO_CLEAN = "start auto clean"
    const val CLEANING_SCREEN_STOP_AUTO_CLEAN = "stop auto clean"

    const val SETTINGS_SCREEN_NAME = "settings"
    const val SETTINGS_SCREEN_UPDATE = "check for update"
}